# Stage status to start server:
#   - "dev", for start server without graceful shutdown
#   - "prod", for start server with graceful shutdown
STAGE_STATUS: "dev"
APP:
  NAME: "golang.fiber.template"
  PORT: 8055
DATABASE:
  HOST: "localhost"
  PORT: 1433
  USER: "sa"
  PASSWORD: "p@ssw0rd"
SECRET:
  KEY: "secret"
  EXPIRE: 15